### PR TITLE
fix: remove findPartsAndAccessories item from header

### PR DESCRIPTION
**Pull request by AdzicMilos**
References [DM-2925](https://smg-au.atlassian.net/browse/DM-2925)

## Motivation and context

[Describe the problem we're solving and lay out the solution]

## Before

[Describe the current behavior and / or add a screenshot of the current state]

## After

[Describe the new behavior and / or add a screenshot of the new state]

## How to test

[Add a deep link and instructions how to verify the new behavior]

### CODE REVIEW

**Review by Milos-Zbiljic — APPROVED** [review]

**Comment by Milos-Zbiljic** [comment]
Don't forget to remove FR translation if needed

**Comment by GutierrezGo** [comment]
> Don't forget to remove FR translation if needed

@Milos-Zbiljic adding and removing translations in the code base there is no need to remove them in phraseApp ☺️ ONLY when you change them

**Review by GutierrezGo — COMMENTED** [review]
I am wondering why the FR translation was not removed.

**Comment by AdzicMilos** [comment]
> I am wondering why the FR translation was not removed.

I did't push Enter after `:w` strong enough.

**Review by GutierrezGo — APPROVED** [review]

**Pull request merged**
