### PR TITLE
fix: enable style props to alert component

### PR DESCRIPTION
**Pull request by AdzicMilos**
References [link the ticket here]

## Motivation and context

Enable to pass  'style props' to component. For example to add margin.

## Before

[Describe the current behavior and / or add a screenshot of the current state]

## After

[Describe the new behavior and / or add a screenshot of the new state]

## How to test

[Add a deep link and instructions how to verify the new behavior]

### CODE REVIEW

**Review by GutierrezGo — CHANGES_REQUESTED** [review]
Please do not add extra props in unified component. We had a list for flexible and strict components. Let us have discuss this. Thank you!

**Comment by AdzicMilos** [comment]
> Please do not add extra props in unified components. We have a list for flexible and strict components, doing this we are hurting the DS. Let us have discuss this. Thank you!

Can you send me the list, I am not aware of that list.

**Comment by GutierrezGo** [comment]
> > Please do not add extra props in unified components. We have a list for flexible and strict components, doing this we are hurting the DS. Let us have discuss this. Thank you!
> 
> Can you send me the list, I am not aware of that list.

What a mean with a list is that we keep on mind the component that need to be more strict. But it would be good to bring this point to the DS glue team

**Comment by talamcol** [comment]
@GutierrezGo could you elaborate what props he added? The props were already enabled before but had no effect. This was clearly a bug in the component. There is no additional prop being whitelisted here

**Comment by GutierrezGo** [comment]
@talamcol please check this PR -> https://github.com/smg-automotive/listings-web/pull/1883
This is an action that I am taking in the Design System. Please find the explanations in the PR.

**Comment by GutierrezGo** [comment]
@AdzicMilos as @talamcol and I discussed, we will close this PR and we will work on this separately because I need to check first with the Design System team about what props should be passed.
We shouldn't whitelisted everything in the components, we need to be aligned with the designers as well and be more restricted here.
Thank you!

**Pull request closed without merging**
