### PR TITLE
fix: tab enclosed variant border & font color

### PR DESCRIPTION
**Pull request by Milos-Zbiljic**
References https://smg-au.atlassian.net/browse/ST-197

## Motivation and context

Removing double border & changing font color in order to improve contrast.

## Before

[Describe the current behavior and / or add a screenshot of the current state]

## After

Screenshot 2024-06-27 at 15 33 20

Screenshot 2024-06-27 at 15 35 06

## How to test

https://fix-enclosed-tab-variant-components-pkg.branch.autoscout24.dev/?path=/docs/components-navigation-tabs--documentation

### CODE REVIEW

**Review by lkappeler — APPROVED** [review]

**Review by lkappeler — COMMENTED** [review]
Can you add the vatiant to the story https://fix-enclosed-tab-variant-components-pkg.branch.autoscout24.dev/?path=/docs/components-navigation-tabs--documentation

**Comment by Milos-Zbiljic** [comment]
> Can you add the vatiant to the story https://fix-enclosed-tab-variant-components-pkg.branch.autoscout24.dev/?path=/docs/components-navigation-tabs--documentation

There is one already, or am I missing something?

Screenshot 2024-06-27 at 16 07 00

**Comment by lkappeler** [comment]
Maybe I am outdated but I had in mind the intention was to add on per variant 
image

**Comment by Milos-Zbiljic** [comment]
> Maybe I am outdated but I had in mind the intention was to add on per variant (I tested it by manually switching the settings) image

Ok, I'll update those as well.

**Pull request merged**
