### PR TITLE
feat: overflow for tabs and more prominent active state

### PR DESCRIPTION
**Pull request by talamcol**
References https://smg-au.atlassian.net/browse/DM-2890

## Motivation and context

It has been discussed with the designers to increase the border to 3px for the tab component. Further, I added horizontal scroll in case there are too many tabs for the width. There is currently a bug left with the applayout that I'll tackle separately

### CODE REVIEW

**Review by mmataja — APPROVED** [review]
Checked locally on branch. LGTM

**Review by NenadRos — APPROVED** [review]

**Comment by NenadRos** [comment]
I haven't worked on components package yet and now wondering how to test your changes and be sure it won't break something on projects?

**Comment by talamcol** [comment]
> I haven't worked on components package yet and now wondering how you test your changes and be sure it won't break something on projects?

I have a PR open in listings-web that will be QA tested with the pre-release version of this change. Once it gets approved, I will merge this one and update the version.

https://github.com/smg-automotive/listings-web/pull/2072

As per seller-web, I just started it locally and compared to the main branch version.

**Comment by NenadRos** [comment]
Thank you. :)

**Pull request merged**
